package br.com.questor.crm.enums;

public enum FaseOportunidadeEnum {
	CONTATO_INICIAL,
	PROSPECT,
	PROSPECT_QUALIFICADO,
	CLIENTE_EM_NEGOCIACAO,
	NEGOCIO_FECHADO,
	NEGOCIO_PERDIDO,
	NEGOCIO_TRANSFERIDO
}
